// This is an example configuration file for the DHCPv4 server in Kea.
// It is a basic scenario with one IPv4 subnet configured. The subnet
// contains a single pool of dynamically allocated addresses.

{ "Dhcp4":

{
// Kea is told to listen on eth0 interface only.
  "interfaces-config": {
    "interfaces": [ "enp0s8" ]
  },

// We need to specify the database used to store leases. 
// We'll use memfile because it doesn't require any prior set up.
  "lease-database": {
      "type": "memfile",
      "lfc-interval": 3600
  },

// Addresses will be assigned with a lifetime of 4000 seconds.
  "valid-lifetime": 4000,

// The following list defines subnets. We have only one subnet
// here. We tell Kea that it is directly available over local interface.
  "subnet4": [
    {
       "pools": [ { "pool":  "192.168.42.100 - 192.168.42.252" } ],
       "id": 1,
       "subnet": "192.168.42.0/24",
       "interface": "enp0s8",
       "valid-lifetime": 7200,
       "max-valid-lifetime": 14400,
       "option-data": [
         {
           "name": "domain-name",
           "data": "linux-training.be"
         },
         {
           "name": "domain-name-servers",
           "data": "10.0.2.3"
         },
         {
           "name": "routers",
           "data": "192.168.42.254"
         }
       ]

    }
  ],

// The following configures logging. It assumes that messages with at
// least informational level (info, warn, error and fatal) should be
// logged to stdout. Alternatively, you can specify stderr here, a filename
// or 'syslog', which will store output messages via syslog.
    "loggers": [
        {
            "name": "kea-dhcp4",
            "output-options": [
                {
                    "output": "stdout"
                }
            ],
            "severity": "INFO"
        }
    ]
}

}
